CREATE TABLE carclass(
    class_id INTEGER ,
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    carclass VARCHAR(20),
    makeandmodel VARCHAR(40),
    comfort VARCHAR(10),
    topspeed VARCHAR(10),
    handling VARCHAR(10),
    crashsafetyrating VARCHAR(10),
    fueleconomy VARCHAR(10)
);